### ISSUE TITLE
Error: package or namespace load failed

### ISSUE THREAD

**Issue by johannesostner** [zellerlab/SIMBA#1]
Hi all!
When trying to install SIMBA (MacOS, R version 4.1.2), I'm running into the following error message:

```
Error: package or namespace load failed for ‘SIMBA’ in namespaceExport(ns, exports):
 undefined exports: confounder.plot
Error: loading failed
Execution halted
```

I suppose that this is caused by the export in the NAMESPACE file, but there seems to be no function called `confounder.plot` in the package.

Thanks for looking into this!

**Comment by jakob-wirbel** [comment]
Hi Johannes,
Thank you for your interest in the package!

First off, the project is far from done and I'm currently still developing the package. That means that it is not yet ready for general use, I guess, and changes that might affect the structure of whole functions can still change 😃
So, be warned about upcoming changes 😃 

But cool that you are generally interested in the package. I think most of the things should be more or less ready to use. And good catch, there is a problem with the `NAMESPACE` because there used to be this function which I removed at some point (but I didn't yet update the NAMESPACE). I will update this as soon as possible, but I am traveling for a conference currently, so it might take a couple of days.

Cheers,
Jakob

**Comment by johannesostner** [comment]
Hi Jakob,
thanks a lot for the quick answer! For now we're only discussing the paper in our journal club, so no need to rush anything. I'm looking forward to seeing the package (especially the data generation with implantation) fully fleshed out, though! 

Best of luck at your conference,
Johannes
